[build]
target = "thumbv7em-none-eabihf"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

# [target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb"

[env]
RUSTC_BOOTSTRAP = "1"