name: Rust Kernel Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add rust-src

      - name: Add target
        run: rustup target add x86_64-tengrios

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build Kernel (bootimage)
        run: cargo build --target x86_64-tengrios

      - name: Run Kernel Tests
        run: cargo test --target x86_64-tengrios
