name: Rust Kernel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly + components
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add rust-src

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build kernel
        run: cargo build

      - name: Run kernel tests
        run: cargo test
